# -*- coding: utf-8 -*-
"""Artwork.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yUcnQ0b7VXeLKgCCmByVzh-2w170YRn8
"""

#Here it imports the MuseumItem class to inherit from it.
from MuseumItem import MuseumItem

# Artwork class that inherits from MuseumItem
class Artwork(MuseumItem):
    #A constructor of Artwork with parameters for all its attributes and those of MuseumItem.
    def __init__(self, title, artist, dateOfCreation, historicalSignificance,
                 material, genre, insuranceValue, subjectMatter):
        # Call the constructor of the parent class (MuseumItem)
        super().__init__(title, artist, dateOfCreation, historicalSignificance)
        # Set the material of the Artwork
        self.material = material
        # Set the genre of the Artwork
        self.genre = genre
        # Set the insurance value of the Artwork
        self.insuranceValue = insuranceValue
        # Set the subject matter of the Artwork
        self.subjectMatter = subjectMatter

    # Getter method for material
    def get_material(self):
        return self.material

    # Setter method for material
    def set_material(self, material):
        self.material = material

    # Getter method for genre
    def get_genre(self):
        return self.genre

    # Setter method for genre
    def set_genre(self, genre):
        self.genre = genre

    # Getter method for insurance value
    def get_insuranceValue(self):
        return self.insuranceValue

    # Setter method for insurance value
    def set_insuranceValue(self, insuranceValue):
        self.insuranceValue = insuranceValue

    # Getter method for subject matter
    def get_subjectMatter(self):
        return self.subjectMatter

    # Setter method for subject matter
    def set_subjectMatter(self, subjectMatter):
        self.subjectMatter = subjectMatter