# -*- coding: utf-8 -*-
"""Exhibition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P9wD2W-dG8uvLHKk-CA08cQx87cscPm3
"""

# Import the Event class to inherit from it.
from Event import Event

# Exhibition class that inherits from Event
class Exhibition(Event):
    #A constructor of Exhibition with parameters for all its attributes and those of Event.
    def __init__(self, name, location, duration, date, items, subjectMatter):
        # Call the constructor of the parent class (Event)
        super().__init__(name, location, duration, date)
        self.items = items  # Set the items being exhibited
        self.subjectMatter = subjectMatter  # Set the subject matter of the Exhibition

    # Getter method for items
    def get_items(self):
        return self.items

    # Setter method for items
    def set_items(self, items):
        self.items = items

    # Getter method for subject matter
    def get_subjectMatter(self):
        return self.subjectMatter

    # Setter method for subject matter
    def set_subjectMatter(self, subjectMatter):
        self.subjectMatter = subjectMatter