# -*- coding: utf-8 -*-
"""MuseumLocationType.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SmIho-L3_8nWoFecT55D1oBTKikitzF6
"""

# Import the Enum class to define enumeration.
from enum import Enum

# MuseumLocationType enumeration definition
class MuseumLocationType(Enum):
    PERMANENT_GALLERY = 1  # Enum member for permanent gallery
    EXHIBITION_HALL = 2    # Enum member for exhibition hall
    OUTDOOR_SPACE = 3      # Enum member for outdoor space