# -*- coding: utf-8 -*-
"""MuseumItem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10oKnSdw7S3r3IS0Hbk587vReHRxpC498
"""

# MuseumItem class definition
class MuseumItem:
    # Constructor of MuseumItem with parameters for all its attributes.
    def __init__(self, title, artist, dateOfCreation, historicalSignificance):
        self.title = title  # Set the title of the MuseumItem
        self.artist = artist  # Set the artist of the MuseumItem
        self.dateOfCreation = dateOfCreation  # Set the date of creation of the MuseumItem
        self.historicalSignificance = historicalSignificance  # Set the historical significance of the MuseumItem

    # Getter method for title
    def get_title(self):
        return self.title

    # Setter method for title
    def set_title(self, title):
        self.title = title

    # Getter method for artist
    def get_artist(self):
        return self.artist

    # Setter method for artist
    def set_artist(self, artist):
        self.artist = artist

    # Getter method for date of creation
    def get_dateOfCreation(self):
        return self.dateOfCreation

    # Setter method for date of creation
    def set_dateOfCreation(self, dateOfCreation):
        self.dateOfCreation = dateOfCreation

    # Getter method for historical significance
    def get_historicalSignificance(self):
        return self.historicalSignificance

    # Setter method for historical significance
    def set_historicalSignificance(self, historicalSignificance):
        self.historicalSignificance = historicalSignificance