# -*- coding: utf-8 -*-
"""Tour.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IUjWVkrqiXr-q36GO5oLVVwub6vIngtW
"""

# Import the Event class to inherit from it.
from Event import Event

# Tour class that inherits from Event
class Tour(Event):
    # Constructor of Tour with parameters for all its attributes and those of Event.
    def __init__(self, name, location, duration, date, guide, capacity):
        # Call the constructor of the parent class (Event)
        super().__init__(name, location, duration, date)
        self.guide = guide  # Set the guide for the Tour
        # Use the setter for capacity to enforce the capacity limits
        self.set_capacity(capacity)

    # Getter method for the guide
    def get_guide(self):
        return self.guide

    # Setter method for the guide
    def set_guide(self, guide):
        self.guide = guide

    # Getter method for the capacity
    def get_capacity(self):
        return self.capacity

    # Setter method for the capacity
    def set_capacity(self, capacity):
        # Check if the capacity is within the valid range, otherwise raise a ValueError
        if 15 <= capacity <= 40:
            self.capacity = capacity
        else:
            raise ValueError("Capacity should be between 15 and 40")